version: "3.9"
services:
  docker_management:
    image: portainer/portainer-ce
    ports:
      - "3636:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse_proxy:
    image: traefik:v2.9.6
    command: --api.insecure=true --providers.docker
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  node_server:
    deploy:
      replicas: 3
    build:
      context: ./express_image
    ports:
        - "3000"
    labels:
        - "traefik.http.routers.nodeserver.rule=Host(`localhost`) && PathPrefix(`/api`)"
  apache_server:
    deploy:
      replicas: 3
    build:
      context: ./apache_php_image
    ports:
        - "80"
    labels:
        - "traefik.http.routers.apache.rule=Host(`localhost`)"
        - "traefik.http.services.apache.loadbalancer.sticky=true"
        - "traefik.http.services.apache.loadbalancer.sticky.cookie.name=test"
