version: "3.9"
services:
  nodeserver:
    build:
      context: ./express_image
    ports:
        - "9091:3000"
    labels:
        - "traefik.http.routers.nodeserver.rule=Host(`localhost`) && PathPrefix(`/api`)"
  apache:
    build:
      context: ./apache_php_image
    ports:
        - "9090:80"
    labels:
        - "traefik.http.routers.apache.rule=Host(`localhost`)"
  reverse-proxy:
    image: traefik:v2.9.6
    command: --api.insecure = true --providers.docker
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
